### ISSUE TITLE
This isnt an issue I just dont know how to send you a message

### ISSUE THREAD

**Issue by CasiniLoogi** [TalionDiscord/Random#1]
Hey talion, It's casini from Mario Royale. I didnt think youd keep this name for that long after the shit that happened. A lot's happened regarding the game, but the reason I'm leaving this message is because I'm wondering if you have any older shit from Mario Royale, anything for archival purposes. My discord is Casini Loogi#8090, I'd much rather use discord than github (I don't know how to use this platform). I'd like to continue this conversation in dms if possible (even if you don't have anything it would be nice to catch up on what's been happening lately).

**Comment by TalionDiscord** [comment]
Hey Casini! It has been a long time. It's good to hear the game is still going. 

As for myself, I've decided to keep away. I came back once, but Cyuubi had a mental breakdown on me because she couldn't handle being in charge of the community that I was able to handle previously, and she seemed to be suffering from a lot of pressure. At that point I cared more about her mental health than the game, especially when she handed me full control and left the server of her own volition. The community at that point still largely hated me because of a bad joke I made that went on for too long and I found myself in charge of a game I no longer cared for with a community that didn't really want me there, despite me only coming back that time because it was requested of me to come by Cyuubi herself, which I believe was now a cry for help on her behalf. I discussed with chrisoman on what to do, if it would be better to just delete the server because A) I wasn't wanted there B) I was in control of the game/community again which I didn't much care for anymore and C) I hated to see Cyuubi suffering the way she was. In the end I did what I felt was best for Cyuubi over the community and deleted the server, to ease the insane pressure she was suffering from. I don't think anybody ever understood this besides me and chrisoman, but it was a mess. I hope Cyuubi understands why I did that, for her. I feel like returning again would just lead me to being tangled in more drama I don't need. People have already made up their minds about me long ago from out of context post screenshots, and I've long since moved on so I have no desire to revisit.

You can share this information to anyone who still cares, I don't mind. As for your request, I've put everything I have into this download:

https://www.mediafire.com/file/s6179lebk2zq9mg/MR.7z/file

I hope it serves the game well. Peace!

**Comment by CasiniLoogi** [comment]
Hey, it's nice to hear back. I fully understood why you deleted the server, I knew Cyuubi was stressed and you did it to help her. It's unfortunate to hear the community's attitude towards your actions considering how much you did for the community. It's nice that, at least from what it sounds like, you've been able to steer away from any drama involved with MR. It was nice catching up, and I wanted to thank you for creating the Mario Royale community, some of us even actively hang out with each other, and I wouldn't have met a lot of the friends I have on discord without MR. Thanks for the assets too, it'll really help with game preservation. It was nice talking to you again, hopefully your online presence stays drama-free from now on. Cya!
